WR-12 #12
PureFour/workoutrivalapp pull request #13
Opened 2020-03-01 21:37 UTC by JakubiM

#12

2020-03-01 22:40 UTC, PureFour commented on app/src/main/java/com/example/workoutrival/SplashScreen.kt
> +            startActivity(Intent(this@SplashScreen, MainActivity::class.java))
Please check service availability...
You may use this endpoint: **http://localhost/actuator/health**  which returns for example: 
```
{
...
     "status" : "UP"
...
}
```

2020-03-03 20:58 UTC, raddyr17 commented on app/src/main/res/layout/activity_splash_screen.xml
> +            android:id="@+id/imageView2"
Niepotrzebne id.

2020-03-03 20:59 UTC, raddyr17 commented on app/src/main/AndroidManifest.xml
> +
<activity android:name=".MainActivity"/>

2020-03-03 20:59 UTC, raddyr17 commented on app/src/main/AndroidManifest.xml
> +
<activity android:name=".MainActivity">

2020-03-03 21:01 UTC, raddyr17 requested changes
Dwie poprawki potem to merge

2020-03-04 19:29 UTC, closed without merging